parameters:
  Butterfly:
    s: 0.8
    a: 0.24
    rotation:
      alpha: 206
      beta: 45
      gamma: 0
  Leafs:
    PP1: 400
    OutlineExpansion: 0.1
    GlueingGap: 0.0
    Background: [17, 17, 17, 0]
  Layout:
    PP1: 400
    GlueingGap: 0.01
    Background: [17, 17, 17, 0]
  Basemap: images/base/blue_marble_august_small.png
